// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZrvyKLA4_1PyUW9DVBtDzLopJLaNOT3Q',
    appId: '1:95343554383:web:38d698a980ab682a31df3a',
    messagingSenderId: '95343554383',
    projectId: 'poket-chef',
    authDomain: 'poket-chef.firebaseapp.com',
    storageBucket: 'poket-chef.firebasestorage.app',
    measurementId: 'G-VHK3PRNXSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMOHJbOHVmkqCyhMEBF-mg9FZkRVI0aU4',
    appId: '1:95343554383:android:d7332bf7c93252ec31df3a',
    messagingSenderId: '95343554383',
    projectId: 'poket-chef',
    storageBucket: 'poket-chef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCONrMVs6jBYXfKBfHXblnwAKIPRgT1LTQ',
    appId: '1:95343554383:ios:e415ce4b7333f61d31df3a',
    messagingSenderId: '95343554383',
    projectId: 'poket-chef',
    storageBucket: 'poket-chef.firebasestorage.app',
    iosClientId: '95343554383-pcs74kdakgsj6e2m4luth8afq98r6adt.apps.googleusercontent.com',
    iosBundleId: 'com.example.poketChefFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCONrMVs6jBYXfKBfHXblnwAKIPRgT1LTQ',
    appId: '1:95343554383:ios:e415ce4b7333f61d31df3a',
    messagingSenderId: '95343554383',
    projectId: 'poket-chef',
    storageBucket: 'poket-chef.firebasestorage.app',
    iosClientId: '95343554383-pcs74kdakgsj6e2m4luth8afq98r6adt.apps.googleusercontent.com',
    iosBundleId: 'com.example.poketChefFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZrvyKLA4_1PyUW9DVBtDzLopJLaNOT3Q',
    appId: '1:95343554383:web:bb74950e01e1b1f531df3a',
    messagingSenderId: '95343554383',
    projectId: 'poket-chef',
    authDomain: 'poket-chef.firebaseapp.com',
    storageBucket: 'poket-chef.firebasestorage.app',
    measurementId: 'G-CFF6QB5V6E',
  );
}
